version: "3.9"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "arunova_203"
      POSTGRES_USER: "arunova_203"
      POSTGRES_PASSWORD: "arunova_203"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/library.sql:/docker-entrypoint-initdb.d/library.sql
      - ./docker/db/scripts/trains.sql:/docker-entrypoint-initdb.d/trains.sql
      - ./docker/db/scripts/hospital.sql:/docker-entrypoint-initdb.d/hospital.sql
      - ./dz:/var/lib/postgresql/data
    ports:
      - "5432:5432"